<?php

namespace Container5joDReJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\main' shared autowired service.
     *
     * @return \App\Controller\main
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/main.php';

        $container->services['App\\Controller\\main'] = $instance = new \App\Controller\main();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\main', $container));

        return $instance;
    }
}
