<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5joDReJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5joDReJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5joDReJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5joDReJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5joDReJ\App_KernelDevDebugContainer([
    'container.build_hash' => '5joDReJ',
    'container.build_id' => 'c173578c',
    'container.build_time' => 1775164283,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5joDReJ');
